server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/market-place-auth-service?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
      format_sql: true
      generate_statistics: true
    hibernate:
      ddl-auto: update


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000