server:
  port: 8083

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/market-place-cart-service?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
      format_sql: true
      generate_statistics: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
